[Rainmeter]
Update=1000
ContextTitle="Open settings"
ContextAction=["NotePad" "#@#UserSettings.ini"]

[Metadata]
Name=Desktop folder launcher
Author=Wickham & Sjoti
Information=A skin to launch any program
License=GPL-3.0
Version=1.0


[Variables]
@Include=#@#UserSettings.ini

SizeIcon=0
C=[!UpdateMeasureGroup Circles][!UpdateMeterGroup Circles][!Redraw]
A=[!UpdateMeasureGroup WaitX][!UpdateMeterGroup WaitX][!Redraw]
I=[!UpdateMeasureGroup Icons][!UpdateMeterGroup Icons][!UpdateMeter MeterSpin][!Redraw]
ChangeIcon=16
Fader=0
IconHider=1
IconSize=64
SpeedDivider=300
IconCircleDistance=16
Resetter=0


[MeasureCalcPosition]
Measure=Calc
Formula=Sin(1/4*PI)

[MeasureCalcPosition2]
Measure=Calc
Formula=Cos(1/4*PI)

[MeasureFader]
Measure=Plugin
Plugin=ActionTimer
Group=Icons
ActionList1=Repeat FadeIn,16,20
FadeIn=[!SetVariable Fader "(Clamp(#Fader#+55,0,1000))"]#I#
ActionList2=Wait 10|Repeat FadeOut,16,33
FadeOut=[!SetVariable Fader "(Clamp(#Fader#-34,0,1000))"]#I#
DynamicVariables=1
UpdateDivider=-1
IfCondition=(#Fader#<1)
IfTrueAction=[!HideMeterGroup Icons]
IfCondition2=(#Fader#>1)
IfTrueAction2=[!ShowMeterGroup Icons]
IfCondition3=(#Fader#>1)
IfTrueAction3=[!HideMeterGroup SmallIcons]
IfCondition4=(#Fader#<=1)
IfTrueAction4=[!ShowMeterGroup SmallIcons]
IgnoreWarnings=1

[MeasureCircleWait]
Measure=Plugin
Plugin=ActionTimer
Group=WaitX
ActionList1=Repeat ClickOn,16,20
ClickOn=[!SetVariable Resetter "(Clamp(#Resetter#+0.5,0,10))"]#A#
ActionList2=Wait 1|Repeat ClickOff,16,20
ClickOff=[!SetVariable Resetter "(Clamp(#Resetter#-0.5,0,10))"]#A#
DynamicVariables=1
UpdateDivider=-1
IgnoreWarnings=1
IfCondition=(#Resetter# > 9)
IfTrueAction=[!CommandMeasure MeasureCircleTimer "Stop 2"][!CommandMeasure MeasureCircleTimer "Execute 1"][!HideMeter MeterSpin]

[MeasureFolder]
Measure=Plugin
Plugin=FileView
Path=#@#Shortcuts
ShowFolder=0
ShowDotDot=0
Count=20

[MeasureScript]
Measure=Script
ScriptFile=#@#GenerateIcons.lua
DynamicVariables=1

[MeasureCircleTimer]
Measure=Plugin
Plugin=ActionTimer
Group=Circles
ActionList1=Repeat ClickOn,16,25
ClickOn=[!SetVariable SizeIcon "(Clamp(#SizeIcon#+0.75,0,#ChangeIcon#))"]#C#
ActionList2=Wait #SpeedDivider#|Repeat ClickOff,16,25
ClickOff=[!SetVariable SizeIcon "(Clamp(#SizeIcon#-0.75,0,#ChangeIcon#))"]#C#
DynamicVariables=1
UpdateDivider=-1
IgnoreWarnings=1
IfCondition=(#SizeIcon# > 0)
IfTrueAction=[!CommandMeasure MeasureCircleWait "Stop 1"][!CommandMeasure MeasureCircleWait "Execute 2"][!HideMeter MeterSpin][!ShowMeter MeterMouseCircle]
IfFalseAction=[!HideMeter MeterMouseCircle][!ShowMeter MeterSpin]#A#
IfCondition2=(#SizeIcon# > (10))
IfTrueAction2=[!CommandMeasure MeasureFader "Stop 2"][!CommandMeasure MeasureFader "Execute 1"]
DynamicVariables=1

[MeterPlaceHolder]
Meter=Image
W=320
H=320
ImageTint=0,0,0,255

[MeasureCalcChange]
Measure=Calc
Group=Icons
Formula=(#IconSize# + 0.5*(0.5*(#SizeIcon# * #SizeIcon#) + (4 * #SizeIcon#)) )

[StyleIcon]
Meter=Image
Group=Icons
Hidden=1
W=58
H=58
ImageTint=255,255,255
DynamicVariables=1
MouseOverAction=[!SetOption #CURRENTSECTION# ImageTint "200,200,200"]#I#
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageTint "255,255,255"]#I#

[StyleIconSmall]
Meter=Image
Group=SmallIcons
Hidden=1
W=29
H=29
ImageTint=255,255,255
DynamicVariables=1

[MeasureIcon1]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=1
IconSize=Large

[MeasureIcon2]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=2
IconSize=Large

[MeasureIcon3]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=3
IconSize=Large

[MeasureIcon4]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=4
IconSize=Large

[MeasureIcon5]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=5
IconSize=Large

[MeasureIcon6]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=6
IconSize=Large

[MeasureIcon7]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=7
IconSize=Large

[MeasureIcon8]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=8
IconSize=Large

[MeasureIcon9]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=9
IconSize=Large

[MeasureIcon10]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=10
IconSize=Large

[MeasureIcon11]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=11
IconSize=Large

[MeasureIcon12]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=12
IconSize=Large

[MeasureIcon13]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=13
IconSize=Large

[MeasureIcon14]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=14
IconSize=Large

[MeasureIcon15]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=15
IconSize=Large

[MeasureIcon16]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=16
IconSize=Large

[MeasureIcon17]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=17
IconSize=Large

[MeasureIcon18]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=18
IconSize=Large

[MeasureIcon19]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=19
IconSize=Large

[MeasureIcon20]
Measure=Plugin
Plugin=FileView
Path=[MeasureFolder]
Type=Icon
Index=20
IconSize=Large



;*********************************************
;Meters/Shortcuts/Icon
;*********************************************

[MeterRoundline]
Meter=Roundline
Group=Circles
Solid=1
X=160
Y=160
LineLength=(#IconSize# + 0.5*(0.5*(#SizeIcon# * #SizeIcon#) + (4 * #SizeIcon#)) )
Linecolor=#CircleColor#
LineStart=(#IconSize#*0.8 + 1.2* (-0.5*(#SizeIcon# * #SizeIcon#) + (4 * #SizeIcon#)) )
StartAngle=0
RotationAngle=6.3
Antialias=1
DynamicVariables=1
Hidden=#HideCircle#

[MeterSpin]
Meter=Roundline
Group=WaitX
Solid=1
X=160
Y=160
LineLength=(#IconSize#)
Linecolor=#LoadingCircleColor#
LineStart=(#IconSize#*0.8)
StartAngle=0
RotationAngle=((#Resetter#/6.3)*6.3)
Antialias=1
DynamicVariables=1
Hidden=#HideCircle#

[MeterMouseCircle]
Meter=Image
ImageName=#@#circle.png
W=(2*(#IconSize# + 0.5 * (0.5*(#ChangeIcon# * #ChangeIcon#) + (4 * #ChangeIcon#))))
H=(2*(#IconSize# + 0.5 * (0.5*(#ChangeIcon# * #ChangeIcon#) + (4 * #ChangeIcon#))))
X=0
Y=0
MouseLeaveAction=[!CommandMeasure MeasureFader "Stop 1"][!CommandMeasure MeasureFader "Execute 2"][!CommandMeasure MeasureCircleTimer "Stop 1"][!CommandMeasure MeasureCircleTimer "Execute 2"][!ShowMeter MeterMouseCircleOver][!HideMeter MeterMouseCircle]
ImageTint=255,255,255,1
DynamicVariables=1




[MeterIcon1]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon1
X=0
Y=0
ImageAlpha=(#Fader# - 100)
LeftMouseUpAction=[!CommandMeasure MeasureIcon1 "Open"]

[MeterIconSmall1]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon1
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-100)

[MeterIcon2]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon2
X=0
Y=0
ImageAlpha=(#Fader# - 150)
LeftMouseUpAction=[!CommandMeasure MeasureIcon2 "Open"]

[MeterIconSmall2]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon2
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-150)

[MeterIcon3]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon3
X=0
Y=0
ImageAlpha=(#Fader# - 200)
LeftMouseUpAction=[!CommandMeasure MeasureIcon3 "Open"]

[MeterIconSmall3]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon3
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-200)

[MeterIcon4]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon4
X=0
Y=0
ImageAlpha=(#Fader# - 250)
LeftMouseUpAction=[!CommandMeasure MeasureIcon4 "Open"]

[MeterIconSmall4]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon4
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-250)

[MeterIcon5]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon5
X=0
Y=0
ImageAlpha=(#Fader# - 300)
LeftMouseUpAction=[!CommandMeasure MeasureIcon5 "Open"]

[MeterIconSmall5]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon5
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-300)

[MeterIcon6]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon6
X=0
Y=0
ImageAlpha=(#Fader# - 350)
LeftMouseUpAction=[!CommandMeasure MeasureIcon6 "Open"]

[MeterIconSmall6]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon6
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-350)

[MeterIcon7]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon7
X=0
Y=0
ImageAlpha=(#Fader# - 400)
LeftMouseUpAction=[!CommandMeasure MeasureIcon7 "Open"]

[MeterIconSmall7]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon7
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-400)

[MeterIcon8]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon8
X=0
Y=0
ImageAlpha=(#Fader# - 450)
LeftMouseUpAction=[!CommandMeasure MeasureIcon8 "Open"]

[MeterIconSmall8]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon8
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-450)

[MeterIcon9]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon9
X=0
Y=0
ImageAlpha=(#Fader# - 500)
LeftMouseUpAction=[!CommandMeasure MeasureIcon9 "Open"]

[MeterIconSmall9]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon9
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-500)

[MeterIcon10]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon10
X=0
Y=0
ImageAlpha=(#Fader# - 550)
LeftMouseUpAction=[!CommandMeasure MeasureIcon10 "Open"]

[MeterIconSmall10]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon10
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-550)

[MeterIcon11]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon11
X=0
Y=0
ImageAlpha=(#Fader# - 600)
LeftMouseUpAction=[!CommandMeasure MeasureIcon11 "Open"]

[MeterIconSmall11]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon11
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-600)

[MeterIcon12]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon12
X=0
Y=0
ImageAlpha=(#Fader# - 650)
LeftMouseUpAction=[!CommandMeasure MeasureIcon12 "Open"]

[MeterIconSmall12]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon12
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-650)

[MeterIcon13]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon13
X=0
Y=0
ImageAlpha=(#Fader# - 700)
LeftMouseUpAction=[!CommandMeasure MeasureIcon13 "Open"]

[MeterIconSmall13]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon13
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-700)

[MeterIcon14]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon14
X=0
Y=0
ImageAlpha=(#Fader# - 750)
LeftMouseUpAction=[!CommandMeasure MeasureIcon14 "Open"]

[MeterIconSmall14]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon14
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-750)

[MeterIcon15]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon15
X=0
Y=0
ImageAlpha=(#Fader# - 800)
LeftMouseUpAction=[!CommandMeasure MeasureIcon15 "Open"]

[MeterIconSmall15]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon15
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-800)

[MeterIcon16]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon16
X=0
Y=0
ImageAlpha=(#Fader# - 850)
LeftMouseUpAction=[!CommandMeasure MeasureIcon16 "Open"]

[MeterIconSmall16]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon16
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-850)

[MeterIcon17]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon17
X=0
Y=0
ImageAlpha=(#Fader# - 900)
LeftMouseUpAction=[!CommandMeasure MeasureIcon17 "Open"]

[MeterIconSmall17]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon17
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-900)

[MeterIcon18]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon18
X=0
Y=0
ImageAlpha=(#Fader# - 950)
LeftMouseUpAction=[!CommandMeasure MeasureIcon18 "Open"]

[MeterIconSmall18]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon18
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-950)

[MeterIcon19]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon19
X=0
Y=0
ImageAlpha=(#Fader# - 1000)
LeftMouseUpAction=[!CommandMeasure MeasureIcon19 "Open"]

[MeterIconSmall19]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon19
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-1000)

[MeterIcon20]
Meter=Image
MeterStyle=StyleIcon
MeasureName=MeasureIcon20
X=0
Y=0
ImageAlpha=(#Fader# - 1050)
LeftMouseUpAction=[!CommandMeasure MeasureIcon20 "Open"]

[MeterIconSmall20]
Meter=Image
MeterStyle=StyleIconSmall
MeasureName=MeasureIcon20
X=0
Y=0
ImageAlpha=(1000-((#Fader#*0.5))-1050)


[Meterstring]
Meter=String
MeterStyle=styleTextControls
Group=Icons|Circles
X=160
Y=(160 - 24)
StringAlign=Center
FontFace=Lato-bold
Text="#Text#"
FontColor=#FontColor#,(#Fader#/4)
FontSize=#FontSize#
ClipString=2
DynamicVariables=1
AntiAlias=1
Hidden=1


[Meterbar]
Meter=Image
Group=Icons
W=#SizeIcon#
H=1
X=150
Y=165
ImageTint=255,255,255,255
ImageAlpha=(#Fader# - 800)
Hidden=1

[MeterIconCenter]
Meter=Image
Group=Circles
X=((128) -0.5 * (-1*(#SizeIcon# * #SizeIcon#) + (12 * #SizeIcon#)) )
Y=((128) -0.5 * (-1*(#SizeIcon# * #SizeIcon#) + (12 * #SizeIcon#)) )
W=(-1*(#SizeIcon# * #SizeIcon#) + (12 * #SizeIcon#) + 64)
H=(-1*(#SizeIcon# * #SizeIcon#) + (12 * #SizeIcon#) + 64)
ImageName=#MainIconPicture#
DynamicVariables=1
Hidden=#HideCenterIcon#

[MeterMouseCircleOver]
Meter=Image
ImageName=#@#circleCenter.png
W=(64)
H=64
X=128
Y=128
MouseOverAction=[!CommandMeasure MeasureCircleWait "Stop 2"][!CommandMeasure MeasureCircleWait "Execute 1"][!ShowMeter MeterMouseCircle]
MouseLeaveAction=[!CommandMeasure MeasureCircleWait "Stop 1"][!CommandMeasure MeasureCircleWait "Execute 2"]
ImageTint=255,255,255,1
DynamicVariables=1
